server:
  port: ${APPLICATION_PORT:8081}
  servlet:
    contextPath: ${APPLICATION_PATH:/api}
  access:
    inner: ${APPLICATION_INNER:http://127.0.0.1:8081}
    outer: ${APPLICATION_OUTER:https://wx.dev.chelizitech.com}
spring:
  application:
    name: ${APPLICATION_NAME:distribution-frontend}
cluster:
  type: "cluster"
  nodes: ${CLUSTER_NODES:192.168.0.1,192.168.0.2,192.168.0.3}
  host: ${CLUSTER_HOST:192.168.0.1}